version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.22.1
    restart: always
    container_name: prometheus
    volumes:
      - ./conf/prometheus:/etc/prometheus
      - ./conf/prometheus/data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:7.3.2
    restart: always
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./conf/grafana:/etc/grafana
      - ./conf/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000